Juno development
codeu-su-19-team-48/team-48-codeu pull request #13
Opened 2019-05-23 19:19 UTC by Junochiu

Close#10
first time making a pull request, Let's see whether "Close #issue_number" works or not!

2019-05-24 06:37 UTC, Sinyu104 reviewed
Did you type `git pull origin master` into the terminal in order to get the most recent version of the master branch from the repo?
Just curious about the reason why the conflict happens. haha~

2019-05-24 06:38 UTC, Sinyu104 commented
> Did you type `git pull origin master` into the terminal in order to get the most recent version of the master branch from the repo?
> Just curious about the reason why the conflict happens. haha~

2019-05-24 06:58 UTC, ahuang13 commented on src/main/webapp/aboutus.html
> +	  through my practice. There's always something to be learnt in a travel! I want to go to every country, Arctic (and maybe bring some pengius back as pets XD like what Mr.Popper did)
```suggestion
	  through my practice. There's always something to be learnt in a travel! I want to go to every country, Arctic (and maybe bring some penguins back as pets XD like what Mr.Popper did)
```

2019-05-24 07:00 UTC, ahuang13 requested changes
It looks like some of the formatting is off. Can you try running "Reformat Code" in IntelliJ (assuming that's the IDE you're using).

2019-05-25 07:09 UTC, 0xAlison approved these changes

2019-05-25 09:08 UTC, Junochiu commented
> reason why the conflict happened

yeah! I missed the step >< That's the reason why the conflict happened.

2019-05-25 10:17 UTC, Sinyu104 approved these changes

2019-05-25 15:29 UTC, ahuang13 approved these changes

2019-05-25 15:29 UTC, merged